- name: Restart and update services
  hosts: home
  tasks:
    - name: Ping my hosts
      ansible.builtin.ping:

    - name: Copy docker-compose.yml
      tags: docker
      ansible.builtin.copy:
        src: docker-compose.yml
        dest: ~/docker-compose.yml
        owner: nat
        mode: u+rw

    - name: Copy my_secret.txt
      tags: docker
      ansible.builtin.copy:
        src: my_secret.txt
        dest: ~/my_secret.txt
        owner: nat
        mode: u+rw

    - name: Stop all services
      tags: docker
      community.docker.docker_compose_v2:
        project_src: /home/nat
        state: stopped
        remove_orphans: true

    - name: Prune everything
      tags: docker
      community.docker.docker_prune:
        builder_cache: true
        images: true
        volumes: false

    - name: Update containers
      tags:
        - docker
        - start
      become: true
      community.docker.docker_compose_v2:
        project_src: /home/nat
        pull: always
        state: present
        build: always
      register: output

    - name: Show docker results
      tags: docker start
      ansible.builtin.debug:
        var: output
