- name: Restart and update services
  hosts: home
  tasks:
    - name: Ping my hosts
      ansible.builtin.ping:

    - name: Update packages
      become: true
      ansible.builtin.apt:
        name: "*"
        state: latest

    - name: Restart server
      become: true
      ansible.builtin.reboot:

    - name: copy docker-compose.yml
      tags: docker
      copy:
        src: docker-compose.yml  
        dest: ~/docker-compose.yml

    - name: copy radicale files
      tags: docker
      copy:
        src: radicale/
        dest: ~/radicale/

    - name: Update containers
      tags: docker
      become: true
      community.docker.docker_compose:
        project_src: /home/nat
        pull: true
        state: present
      register: output

    - name: Show docker results
      tags: docker
      ansible.builtin.debug:
        var: output
