- name: Restart and update services
  hosts: home
  tasks:
    - name: Ping my hosts
      ansible.builtin.ping:

    - name: Update packages
      become: true
      ansible.builtin.apt:
        name: "*"
        state: latest

    - name: Restart server
      become: true
      ansible.builtin.reboot:

    - name: Copy docker-compose.yml
      tags: docker
      ansible.builtin.copy:
        src: docker-compose.yml
        dest: ~/docker-compose.yml
        owner: nat
        mode: u+rw
    - name: Copy radicale files
      tags: docker
      ansible.builtin.copy:
        src: radicale/
        dest: ~/radicale/
        owner: nat
        mode: u+rw

    - name: Stop all services
      tags: docker
      community.docker.docker_compose_v2:
        project_src: /home/nat
        build: false
        stopped: true

    - name: Update containers
      tags: docker
      become: true
      community.docker.docker_compose_v2:
        project_src: /home/nat
        pull: true
        state: present
      register: output

    - name: Show docker results
      tags: docker
      ansible.builtin.debug:
        var: output
