volumes:
  kanboard_data:
  kanboard_plugins:
  kanboard_ssl:
  db:
  miniflux-db:

services:
  miniflux:
    image: miniflux/miniflux:latest
    restart: unless-stopped
    ports:
      - "8082:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://miniflux:secret@db/miniflux?sslmode=disable
      - RUN_MIGRATIONS=1
      - CREATE_ADMIN=0
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=test123
      - BASE_URL=http://raspberrypi:8082
      - FETCH_YOUTUBE_WATCH_TIME=1
      # - POLLING_PARSING_ERROR_LIMIT=0
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      - POSTGRES_USER=miniflux
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=miniflux
    volumes:
      - miniflux-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "miniflux"]
      interval: 10s
      start_period: 30s
  kanboard:
    image: kanboard/kanboard:latest
    restart: unless-stopped
    ports:
      - "8083:80"
      # - "443:443"
    environment:
      - PLUGIN_INSTALLER=true
    volumes:
      - kanboard_data:/var/www/app/data
      - kanboard_plugins:/var/www/app/plugins
      - kanboard_ssl:/etc/nginx/ssl
